### PR TITLE
Update mod list command

### PR DESCRIPTION
**Pull request by j10a1n15**
This pull request updates the mod list command by adding a new search subcommand and increasing the amount of mods displayed per page. It also includes improvements to the code structure and bug fixes.

### CODE REVIEW

**Comment by Su386yt** [comment]
will it crash

**Comment by j10a1n15** [comment]
works fo rme lol

**Comment by j10a1n15** [comment]
do we ever check for merge conflicts here

**Comment by j10a1n15** [comment]
oh yeah

**Comment by j10a1n15** [comment]
seems to work (on my end)

**Comment by Su386yt** [comment]
*can a hypixel non crash it

image

image

image

image

image

image

image

image

image

image

# Multi parter:
image

image

image

image

image





image

# favourite

image

**Comment by j10a1n15** [comment]
Thank you I enjoyed this too much

**Pull request merged**
